export const GET_PRODUCTS = "GET_PRODUCTS";
export const ISLOADING = "ISLOADING";
export const GET_PRODUCTS_WITH_CART = "GET_PRODUCTS_WITH_CART";
export const GET_PRODUCTS_WITH_ID = "GET_PRODUCTS_WITH_ID";

export const ADD_USER= "ADD_USER";